"""
DOCX Generator for ScorCraft (CraftQ output).

Produces a polished, corporate-styled resume as a .docx byte stream from the
structured JSON emitted by services/ai_processor.py.

Design goals (mirrors services/pdf_generator.generate_resume_pdf):
  • Navy header band with candidate name + contact line
  • EXECUTIVE SUMMARY as bullets
  • CORE COMPETENCIES table (fixed widths, word-wrap — no overflow)
  • EMPLOYMENT HISTORY nested: Company → Projects → responsibilities
  • EDUCATION & CERTIFICATIONS, certs as a table with an Expiry column
    (missing expiry rendered as "⚠ Not specified" — a recruiter flag)
  • TECHNICAL COMPETENCIES
  • Letterhead footer: "Generated by RecruitCraft · {company} · Confidential"

Action items / missing-info reports are INTERNAL ONLY and never rendered here.

Public API:
    create_corporate_resume(data, company_name="HYROI Solutions",
                            mask_contacts=False) -> bytes
"""
import io

from docx import Document
from docx.shared import Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


# ── Brand colors (match pdf_generator / spec) ────────────────────
NAVY = RGBColor(0x1A, 0x27, 0x44)
GOLD = RGBColor(0xC8, 0x96, 0x3E)
DARK = RGBColor(0x1F, 0x29, 0x37)
GRAY = RGBColor(0x6B, 0x72, 0x80)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
LIGHT_NAVY = RGBColor(0x2D, 0x4A, 0x6F)

# ScorQ scorecard category colors (match pdf_generator / spec).
BLUE = RGBColor(0x25, 0x63, 0xEB)    # technical
GREEN = RGBColor(0x05, 0x96, 0x69)   # experience / stability
PURPLE = RGBColor(0x7C, 0x3A, 0xED)  # education
INDIGO = RGBColor(0x43, 0x38, 0xCA)  # matched-skill chip text
AI_LABEL = RGBColor(0xC2, 0x41, 0x0C)
AI_TEXT = RGBColor(0x9A, 0x34, 0x12)

# Light fills (hex strings for cell shading).
BANNER_FILL = "F8FAFC"
CHIP_FILL = "EEF2FF"
CARD_FILL = "F9FAFB"
AI_FILL = "FFF7ED"

# ScorQ scorecard categories: (full_label, short_label, key, RGBColor, hex_fill)
_SC_CATS = [
    ("Technical Skills", "Technical", "technical", BLUE, "EFF6FF"),
    ("Experience", "Experience", "experience", GREEN, "ECFDF5"),
    ("Education", "Education", "education", PURPLE, "F5F3FF"),
    ("Stability", "Stability", "stability", GREEN, "ECFDF5"),
]


def _set_cell_background(cell, hex_color: str):
    """Shade a table cell (hex without '#')."""
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tc_pr.append(shd)


def _set_table_bottom_border(table, hex_color="C8963E", sz="12"):
    """Add a colored bottom border to every cell in the table's last row
    (used for the gold rule under the branded banner)."""
    tbl_pr = table._tbl.tblPr
    borders = OxmlElement("w:tblBorders")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), sz)
    bottom.set(qn("w:space"), "0")
    bottom.set(qn("w:color"), hex_color)
    borders.append(bottom)
    tbl_pr.append(borders)


def _sc_score(category_scores, key):
    """(score, reasoning) from a category_scores entry (dict or scalar)."""
    val = (category_scores or {}).get(key)
    if isinstance(val, dict):
        return val.get("score"), (val.get("reasoning") or "")
    return val, ""


def _pct(score):
    if score is None or score == "":
        return "—"
    try:
        return f"{int(round(float(score)))}%"
    except (TypeError, ValueError):
        return str(score)


def _set_table_fixed_layout(table, col_widths_cm):
    """
    Force a fixed table layout so long text wraps inside cells instead of
    overflowing (spec rule: tables must never overflow).
    """
    table.autofit = False
    table.allow_autofit = False
    tbl_pr = table._tbl.tblPr
    layout = OxmlElement("w:tblLayout")
    layout.set(qn("w:type"), "fixed")
    tbl_pr.append(layout)
    for row in table.rows:
        for idx, width in enumerate(col_widths_cm):
            row.cells[idx].width = Cm(width)


def _style_header_cell(cell, text):
    """Navy header row cell with white bold text."""
    _set_cell_background(cell, "1A2744")
    cell.paragraphs[0].text = ""
    run = cell.paragraphs[0].add_run(text)
    run.bold = True
    run.font.size = Pt(9)
    run.font.color.rgb = WHITE


def _body_cell(cell, text):
    cell.paragraphs[0].text = ""
    run = cell.paragraphs[0].add_run(text or "")
    run.font.size = Pt(9)
    run.font.color.rgb = DARK


def _section_heading(doc, text):
    p = doc.add_paragraph()
    p.space_before = Pt(8)
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(11)
    run.font.color.rgb = NAVY
    # Gold underline rule
    p_border = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "6")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "2D4A6F")
    p_border.append(bottom)
    p.paragraph_format.element.get_or_add_pPr().append(p_border)
    return p


def _bullet(doc, text, indent_cm=0.6):
    p = doc.add_paragraph()
    p.paragraph_format.left_indent = Cm(indent_cm)
    p.paragraph_format.space_after = Pt(1)
    run = p.add_run(f"• {text}")
    run.font.size = Pt(9)
    run.font.color.rgb = DARK
    return p


def _setup_page(doc):
    """Standard A4-ish margins for the resume document."""
    section = doc.sections[0]
    section.left_margin = Cm(1.5)
    section.right_margin = Cm(1.5)
    section.top_margin = Cm(1.2)
    section.bottom_margin = Cm(1.8)


def _set_section_footer(section, text, color=GRAY):
    """Centered letterhead footer text on the given section. Unlinks from the
    previous section so the combined DOCX can carry a distinct ScorQ footer on
    the scorecard section."""
    section.footer.is_linked_to_previous = False
    p = section.footer.paragraphs[0]
    p.text = ""
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(text)
    run.font.size = Pt(7)
    run.font.color.rgb = color


def _add_brand_banner(doc, logo_bytes, company_name, company_tagline):
    """Branded banner strip: logo (left) + company name/tagline (right), on a
    light-gray fill with a gold bottom rule. Mirrors the PDF banner. Falls back
    to company-name text on the left when no/invalid logo is supplied."""
    tbl = doc.add_table(rows=1, cols=2)
    _set_table_fixed_layout(tbl, [7.0, 10.0])
    left, right = tbl.rows[0].cells
    _set_cell_background(left, BANNER_FILL)
    _set_cell_background(right, BANNER_FILL)

    left.paragraphs[0].text = ""
    placed = False
    if logo_bytes:
        try:
            run = left.paragraphs[0].add_run()
            run.add_picture(io.BytesIO(logo_bytes), height=Cm(0.85))
            placed = True
        except Exception:
            placed = False
    if not placed:
        lrun = left.paragraphs[0].add_run(company_name or "HYROI Solutions")
        lrun.bold = True
        lrun.font.size = Pt(11)
        lrun.font.color.rgb = NAVY

    rp = right.paragraphs[0]
    rp.text = ""
    rp.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    nrun = rp.add_run(company_name or "HYROI Solutions")
    nrun.bold = True
    nrun.font.size = Pt(10)
    nrun.font.color.rgb = NAVY
    if company_tagline:
        tp = right.add_paragraph()
        tp.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        trun = tp.add_run(company_tagline)
        trun.font.size = Pt(8)
        trun.font.color.rgb = NAVY

    _set_table_bottom_border(tbl, "C8963E", "12")
    doc.add_paragraph()


def _build_resume_body(doc, data, mask_contacts=False, logo_bytes=None,
                       company_name="HYROI Solutions", company_tagline=None,
                       include_header=True):
    """Append the crafted-resume content to `doc` (no margins/footer/save).
    Shared by create_corporate_resume and create_combined_docx.

    `include_header` adds the branded banner (logo + company) at the very top;
    when False the resume starts directly with the navy candidate band.
    """
    candidate = data.get("candidate_info", {}) or {}

    # ── Branded banner strip (logo + company) — header toggle ────
    if include_header:
        _add_brand_banner(doc, logo_bytes, company_name, company_tagline)

    # ── Header band (navy) ───────────────────────────────────────
    header_tbl = doc.add_table(rows=1, cols=1)
    _set_table_fixed_layout(header_tbl, [17.0])
    hcell = header_tbl.rows[0].cells[0]
    _set_cell_background(hcell, "1A2744")
    hcell.paragraphs[0].text = ""

    name_run = hcell.paragraphs[0].add_run(
        (candidate.get("full_name") or "CANDIDATE").upper()
    )
    name_run.bold = True
    name_run.font.size = Pt(16)
    name_run.font.color.rgb = WHITE

    contact_parts = []
    if not mask_contacts:
        if candidate.get("phone"):
            contact_parts.append(candidate["phone"])
        if candidate.get("email"):
            contact_parts.append(candidate["email"])
    loc = candidate.get("current_location") or candidate.get("location")
    if loc:
        contact_parts.append(loc)
    if contact_parts:
        cp = hcell.add_paragraph()
        crun = cp.add_run(" | ".join(contact_parts))
        crun.font.size = Pt(9)
        crun.font.color.rgb = RGBColor(0xB0, 0xC4, 0xDE)

    doc.add_paragraph()

    # ── Executive Summary ────────────────────────────────────────
    summary = data.get("executive_summary", []) or []
    if summary:
        _section_heading(doc, "EXECUTIVE SUMMARY")
        for point in summary[:12]:
            _bullet(doc, point)

    # ── Core Competencies (table) ────────────────────────────────
    competencies = data.get("core_competencies", []) or []
    if competencies:
        _section_heading(doc, "CORE COMPETENCIES")
        tbl = doc.add_table(rows=1, cols=3)
        tbl.style = "Table Grid"
        _set_table_fixed_layout(tbl, [4.5, 5.5, 6.0])
        hdr = tbl.rows[0].cells
        _style_header_cell(hdr[0], "Domain")
        _style_header_cell(hdr[1], "Skills")
        _style_header_cell(hdr[2], "Tools / Technologies")
        for c in competencies:
            row = tbl.add_row().cells
            _body_cell(row[0], c.get("domain", ""))
            _body_cell(row[1], c.get("skills", ""))
            _body_cell(row[2], c.get("tools", ""))

    # ── Employment History (nested) ──────────────────────────────
    employment = data.get("employment_history", []) or []
    if employment:
        _section_heading(doc, "EMPLOYMENT HISTORY")
        for emp in employment[:6]:
            p = doc.add_paragraph()
            p.paragraph_format.space_before = Pt(6)
            run = p.add_run(f"{emp.get('company', '')} — {emp.get('role', '')}")
            run.bold = True
            run.font.size = Pt(10)
            run.font.color.rgb = DARK
            if emp.get("location"):
                lrun = p.add_run(f"  |  {emp['location']}")
                lrun.font.size = Pt(9)
                lrun.font.color.rgb = GRAY
            if emp.get("duration"):
                dp = doc.add_paragraph()
                drun = dp.add_run(emp["duration"])
                drun.font.size = Pt(8)
                drun.font.color.rgb = GRAY

            for proj in emp.get("projects", [])[:4]:
                pp = doc.add_paragraph()
                pp.paragraph_format.left_indent = Cm(0.5)
                ptitle = proj.get("project_name", "")
                if proj.get("client"):
                    ptitle += f" — {proj['client']}"
                if proj.get("duration"):
                    ptitle += f" ({proj['duration']})"
                prun = pp.add_run(ptitle)
                prun.bold = True
                prun.font.size = Pt(9)
                prun.font.color.rgb = LIGHT_NAVY

                for resp in proj.get("responsibilities", [])[:7]:
                    _bullet(doc, resp, indent_cm=1.1)

                if proj.get("technical_skills"):
                    tp = doc.add_paragraph()
                    tp.paragraph_format.left_indent = Cm(1.1)
                    trun = tp.add_run(f"Tech: {proj['technical_skills']}")
                    trun.italic = True
                    trun.font.size = Pt(8)
                    trun.font.color.rgb = GRAY

    # Fallback: flat project_experience (old CraftQ format)
    elif data.get("project_experience"):
        _section_heading(doc, "PROJECT EXPERIENCE")
        for proj in data["project_experience"][:6]:
            parts = []
            if proj.get("project_name"):
                parts.append(proj["project_name"])
            if proj.get("client"):
                parts.append(f"Client: {proj['client']}")
            if proj.get("role"):
                parts.append(f"Role: {proj['role']}")
            if proj.get("duration"):
                parts.append(proj["duration"])
            p = doc.add_paragraph()
            run = p.add_run(" | ".join(parts))
            run.bold = True
            run.font.size = Pt(9)
            for resp in proj.get("responsibilities", [])[:7]:
                _bullet(doc, resp)

    # ── Education & Certifications ───────────────────────────────
    _section_heading(doc, "EDUCATION & CERTIFICATIONS")
    for edu in data.get("education", []) or []:
        parts = []
        if edu.get("degree"):
            parts.append(edu["degree"])
        if edu.get("institution"):
            parts.append(edu["institution"])
        if edu.get("year"):
            parts.append(str(edu["year"]))
        p = doc.add_paragraph()
        run = p.add_run(" — ".join(parts))
        run.font.size = Pt(9)
        run.font.color.rgb = DARK

    certs = data.get("certifications", []) or []
    if certs:
        tbl = doc.add_table(rows=1, cols=3)
        tbl.style = "Table Grid"
        _set_table_fixed_layout(tbl, [7.5, 4.0, 4.5])
        hdr = tbl.rows[0].cells
        _style_header_cell(hdr[0], "Certification")
        _style_header_cell(hdr[1], "Issuer")
        _style_header_cell(hdr[2], "Expiry")
        for cert in certs:
            row = tbl.add_row().cells
            if isinstance(cert, str):
                _body_cell(row[0], cert)
                _body_cell(row[1], "—")
                _body_cell(row[2], "—")
            else:
                _body_cell(row[0], cert.get("name", ""))
                _body_cell(row[1], cert.get("issuer", "—"))
                _body_cell(row[2], cert.get("expiry") or "⚠ Not specified")

    # ── Technical Competencies ───────────────────────────────────
    tech = data.get("technical_competencies", {}) or {}
    if tech and any(tech.values()):
        _section_heading(doc, "TECHNICAL COMPETENCIES")
        for label, key in [
            ("Programming Languages", "programming_languages"),
            ("Tools & Technologies", "tools_technologies"),
            ("Platforms", "platforms"),
        ]:
            if tech.get(key):
                p = doc.add_paragraph()
                lrun = p.add_run(f"{label}: ")
                lrun.bold = True
                lrun.font.size = Pt(9)
                lrun.font.color.rgb = DARK
                vrun = p.add_run(tech[key])
                vrun.font.size = Pt(9)
                vrun.font.color.rgb = DARK

    return doc


def create_corporate_resume(
    data: dict,
    company_name: str = "HYROI Solutions",
    mask_contacts: bool = False,
    logo_bytes: bytes = None,
    company_tagline: str = None,
    include_header: bool = True,
    include_footer: bool = True,
) -> bytes:
    """
    Build the crafted resume DOCX and return it as bytes.

    `data` is the structured JSON from ai_processor.extract_and_structure_resume.
    `mask_contacts` removes email + phone from the header when True (PI masking).
    `include_header` toggles the branded banner; `include_footer` toggles the
    letterhead footer.
    """
    doc = Document()
    _setup_page(doc)
    _build_resume_body(
        doc, data, mask_contacts=mask_contacts, logo_bytes=logo_bytes,
        company_name=company_name, company_tagline=company_tagline,
        include_header=include_header,
    )
    if include_footer:
        _set_section_footer(
            doc.sections[-1],
            f"Generated by RecruitCraft · {company_name} · Confidential",
        )

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()


# ═════════════════════════════════════════════════════════════════
# SCORECARD (DOCX) — structured tables that mimic the ScorQ PDF/UI
# ═════════════════════════════════════════════════════════════════

def _white_run(cell, text, size, bold=True, align=None):
    cell.paragraphs[0].text = ""
    if align is not None:
        cell.paragraphs[0].alignment = align
    run = cell.paragraphs[0].add_run(text or "")
    run.bold = bold
    run.font.size = Pt(size)
    run.font.color.rgb = WHITE


def _build_scorecard_body(doc, sc):
    """Append a one-page ScorQ scorecard rendered as python-docx tables.

    `sc` is a dict: candidate_name, candidate_email, candidate_phone,
    overall_score, category_scores, matched_skills, highlights, ai_reasoning,
    job_title. No pdf2image / poppler — pure table layout."""
    category_scores = sc.get("category_scores") or {}

    # ── Navy header: ScorQ branding (L) + CANDIDATE SCORECARD (R) ──
    head = doc.add_table(rows=1, cols=2)
    _set_table_fixed_layout(head, [10.0, 7.0])
    hl, hr = head.rows[0].cells
    _set_cell_background(hl, "1A2744")
    _set_cell_background(hr, "1A2744")
    hl.paragraphs[0].text = ""
    r1 = hl.paragraphs[0].add_run("Scor")
    r1.bold = True; r1.font.size = Pt(16); r1.font.color.rgb = WHITE
    r2 = hl.paragraphs[0].add_run("Q")
    r2.bold = True; r2.font.size = Pt(16); r2.font.color.rgb = GOLD
    r3 = hl.paragraphs[0].add_run("  by HYROI Solutions")
    r3.font.size = Pt(8); r3.font.color.rgb = RGBColor(0xB9, 0xC2, 0xCF)
    _white_run(hr, "CANDIDATE SCORECARD", 8, bold=True,
               align=WD_ALIGN_PARAGRAPH.RIGHT)

    doc.add_paragraph()

    # ── Candidate name + contacts ────────────────────────────────
    np = doc.add_paragraph()
    nrun = np.add_run(sc.get("candidate_name") or "Candidate")
    nrun.bold = True; nrun.font.size = Pt(17); nrun.font.color.rgb = NAVY
    contact_bits = [b for b in (sc.get("candidate_email"), sc.get("candidate_phone")) if b]
    if contact_bits:
        cpp = doc.add_paragraph()
        crun = cpp.add_run("  ·  ".join(contact_bits))
        crun.font.size = Pt(9); crun.font.color.rgb = GRAY

    # ── Score boxes: 4 category cells, colored value + label ─────
    boxes = doc.add_table(rows=1, cols=4)
    _set_table_fixed_layout(boxes, [4.25, 4.25, 4.25, 4.25])
    for cell, (full, short, key, color, fill) in zip(boxes.rows[0].cells, _SC_CATS):
        score, _ = _sc_score(category_scores, key)
        _set_cell_background(cell, fill)
        cell.paragraphs[0].text = ""
        cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
        lr = cell.paragraphs[0].add_run(short)
        lr.bold = True; lr.font.size = Pt(8); lr.font.color.rgb = color
        vp = cell.add_paragraph()
        vp.alignment = WD_ALIGN_PARAGRAPH.CENTER
        vr = vp.add_run(_pct(score))
        vr.bold = True; vr.font.size = Pt(15)
        vr.font.color.rgb = color if score is not None else GRAY

    doc.add_paragraph()

    # ── Score breakdown: colored-header card per category ────────
    _section_heading(doc, "SCORE BREAKDOWN")
    for full, short, key, color, fill in _SC_CATS:
        score, reasoning = _sc_score(category_scores, key)
        t = doc.add_table(rows=1, cols=2)
        _set_table_fixed_layout(t, [13.0, 4.0])
        cname, cval = t.rows[0].cells
        _set_cell_background(cname, fill)
        _set_cell_background(cval, fill)
        cname.paragraphs[0].text = ""
        cr = cname.paragraphs[0].add_run(full)
        cr.bold = True; cr.font.size = Pt(10); cr.font.color.rgb = color
        cval.paragraphs[0].text = ""
        cval.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.RIGHT
        vr = cval.paragraphs[0].add_run(_pct(score))
        vr.bold = True; vr.font.size = Pt(11)
        vr.font.color.rgb = color if score is not None else GRAY
        if reasoning:
            rp = doc.add_paragraph()
            rp.paragraph_format.left_indent = Cm(0.2)
            rr = rp.add_run(reasoning[:280])
            rr.font.size = Pt(8.5); rr.font.color.rgb = RGBColor(0x4B, 0x55, 0x63)

    # ── Matched skills (indigo chips, wrapped into a grid) ───────
    matched = [str(s).strip() for s in (sc.get("matched_skills") or []) if str(s).strip()][:20]
    if matched:
        doc.add_paragraph()
        _section_heading(doc, "MATCHED SKILLS")
        cols = 4
        rows = (len(matched) + cols - 1) // cols
        grid = doc.add_table(rows=rows, cols=cols)
        _set_table_fixed_layout(grid, [4.25, 4.25, 4.25, 4.25])
        for idx, skill in enumerate(matched):
            cell = grid.rows[idx // cols].cells[idx % cols]
            _set_cell_background(cell, CHIP_FILL)
            cell.paragraphs[0].text = ""
            cell.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER
            sr = cell.paragraphs[0].add_run(skill)
            sr.font.size = Pt(8); sr.font.color.rgb = INDIGO
        # Blank trailing cells stay unshaded (no fill applied).

    # ── Highlights (card) ────────────────────────────────────────
    highlights = sc.get("highlights") or []
    if highlights:
        doc.add_paragraph()
        _section_heading(doc, "HIGHLIGHTS")
        box = doc.add_table(rows=1, cols=1)
        _set_table_fixed_layout(box, [17.0])
        bcell = box.rows[0].cells[0]
        _set_cell_background(bcell, CARD_FILL)
        bcell.paragraphs[0].text = ""
        for i, h in enumerate(highlights[:5]):
            p = bcell.paragraphs[0] if i == 0 else bcell.add_paragraph()
            run = p.add_run(f"•  {str(h)[:200]}")
            run.font.size = Pt(9); run.font.color.rgb = RGBColor(0x37, 0x41, 0x51)

    # ── AI assessment (amber box) ────────────────────────────────
    ai = sc.get("ai_reasoning")
    if ai:
        doc.add_paragraph()
        box = doc.add_table(rows=1, cols=1)
        _set_table_fixed_layout(box, [17.0])
        bcell = box.rows[0].cells[0]
        _set_cell_background(bcell, AI_FILL)
        bcell.paragraphs[0].text = ""
        lab = bcell.paragraphs[0].add_run("AI ASSESSMENT")
        lab.bold = True; lab.font.size = Pt(9); lab.font.color.rgb = AI_LABEL
        tp = bcell.add_paragraph()
        tr = tp.add_run(str(ai)[:1200])
        tr.font.size = Pt(9); tr.font.color.rgb = AI_TEXT

    return doc


def create_combined_docx(
    structured_data: dict,
    scorecard: dict,
    company_name: str = "HYROI Solutions",
    mask_contacts: bool = False,
    logo_bytes: bytes = None,
    company_tagline: str = None,
    include_header: bool = True,
    include_footer: bool = True,
) -> bytes:
    """Combined DOCX: crafted resume pages followed by the scorecard rendered as
    a structured table page (last section). The resume pages follow the
    include_header / include_footer toggles; the scorecard section always keeps
    its own ScorQ footer."""
    from docx.enum.section import WD_SECTION

    doc = Document()
    _setup_page(doc)

    # ── Resume section ───────────────────────────────────────────
    _build_resume_body(
        doc, structured_data, mask_contacts=mask_contacts, logo_bytes=logo_bytes,
        company_name=company_name, company_tagline=company_tagline,
        include_header=include_header,
    )
    if include_footer:
        _set_section_footer(
            doc.sections[-1],
            f"Generated by RecruitCraft · {company_name} · Confidential",
        )

    # ── Scorecard on a new section/page with its own ScorQ footer ─
    doc.add_section(WD_SECTION.NEW_PAGE)
    _build_scorecard_body(doc, scorecard or {})
    _set_section_footer(
        doc.sections[-1], "Generated by ScorQ · HYROI Solutions"
    )

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()
