"""
PDF Generator for ScorCraft.

Three outputs:
  1. generate_resume_pdf()    — formatted resume only
  2. generate_scorecard_pdf() — ScorQ scorecard (matches existing design)
  3. generate_combined_pdf()  — resume pages + scorecard as last page

Action items are NEVER included — they're internal-only.
"""
import io
import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm, mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, Image as RLImage,
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT


# ── Brand colors ─────────────────────────────────────────────
NAVY = colors.HexColor("#1A2744")
GOLD = colors.HexColor("#C8963E")
LIGHT_NAVY = colors.HexColor("#2D4A6F")
DARK = colors.HexColor("#1F2937")
GRAY = colors.HexColor("#6B7280")
LIGHT_BG = colors.HexColor("#F5F7FA")
WHITE = colors.white
GREEN = colors.HexColor("#059669")
RED = colors.HexColor("#DC2626")
AMBER = colors.HexColor("#D97706")
BLUE = colors.HexColor("#2563EB")
PURPLE = colors.HexColor("#7C3AED")
ORANGE = colors.HexColor("#EA580C")
TEAL = colors.HexColor("#0891B2")


def _get_styles():
    """Shared styles for resume and scorecard."""
    styles = getSampleStyleSheet()

    styles.add(ParagraphStyle("SectionHeading", fontName="Helvetica-Bold", fontSize=11,
        textColor=NAVY, spaceBefore=10, spaceAfter=4))
    styles.add(ParagraphStyle("Body", fontName="Helvetica", fontSize=9,
        textColor=DARK, leading=13, spaceAfter=2))
    styles.add(ParagraphStyle("Bullet", fontName="Helvetica", fontSize=9,
        textColor=DARK, leading=13, leftIndent=12, spaceAfter=1))
    styles.add(ParagraphStyle("CompanyHeader", fontName="Helvetica-Bold", fontSize=10,
        textColor=DARK, spaceBefore=6, spaceAfter=1))
    styles.add(ParagraphStyle("ProjectHeader", fontName="Helvetica-Bold", fontSize=9,
        textColor=LIGHT_NAVY, leftIndent=12, spaceBefore=3, spaceAfter=1))
    styles.add(ParagraphStyle("SmallGray", fontName="Helvetica", fontSize=8,
        textColor=GRAY))
    styles.add(ParagraphStyle("NameStyle", fontName="Helvetica-Bold", fontSize=16,
        textColor=WHITE, leading=20))
    styles.add(ParagraphStyle("ContactStyle", fontName="Helvetica", fontSize=9,
        textColor=colors.HexColor("#B0C4DE")))
    styles.add(ParagraphStyle("ScorecardTitle", fontName="Helvetica-Bold", fontSize=12,
        textColor=NAVY, spaceBefore=6, spaceAfter=4))
    styles.add(ParagraphStyle("ScoreLabel", fontName="Helvetica-Bold", fontSize=9,
        textColor=NAVY))
    styles.add(ParagraphStyle("Reasoning", fontName="Helvetica", fontSize=9,
        textColor=DARK, leading=13, spaceAfter=4))

    return styles


def _score_color(score):
    if score >= 75:
        return GREEN
    elif score >= 55:
        return AMBER
    return RED


def _add_footer(canvas, doc, company_name="HYROI Solutions", logo_path=None):
    """Add branded footer to every page."""
    canvas.saveState()
    canvas.setStrokeColor(GOLD)
    canvas.setLineWidth(1.5)
    canvas.line(1.5 * cm, 1.8 * cm, A4[0] - 1.5 * cm, 1.8 * cm)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(GRAY)
    canvas.drawString(1.5 * cm, 1.2 * cm, f"Generated by ScorCraft · {company_name}")
    canvas.drawRightString(A4[0] - 1.5 * cm, 1.2 * cm,
        datetime.now().strftime("%d/%m/%Y"))
    canvas.restoreState()


# ═════════════════════════════════════════════════════════════
# 1. RESUME PDF
# ═════════════════════════════════════════════════════════════

def generate_resume_pdf(
    data: dict,
    company_name: str = "HYROI Solutions",
    mask_contacts: bool = False,
    logo_path: str = None,
) -> bytes:
    """Generate formatted resume as PDF."""
    buffer = io.BytesIO()
    styles = _get_styles()

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=1.5 * cm, rightMargin=1.5 * cm,
        topMargin=1.2 * cm, bottomMargin=2.2 * cm,
    )

    story = []
    candidate = data.get("candidate_info", {})

    # ── Header ───────────────────────────────────────────────
    contact_parts = []
    if not mask_contacts:
        if candidate.get("phone"):
            contact_parts.append(candidate["phone"])
        if candidate.get("email"):
            contact_parts.append(candidate["email"])
    if candidate.get("current_location") or candidate.get("location"):
        contact_parts.append(candidate.get("current_location") or candidate.get("location"))

    name_para = Paragraph(
        candidate.get("full_name", "CANDIDATE").upper(),
        styles["NameStyle"],
    )
    contact_para = Paragraph(" | ".join(contact_parts), styles["ContactStyle"])

    header_table = Table(
        [[[name_para, contact_para]]],
        colWidths=[16 * cm],
    )
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 8))

    def section_heading(text):
        story.append(Paragraph(text, styles["SectionHeading"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=LIGHT_NAVY, spaceAfter=4))

    # ── Executive Summary ────────────────────────────────────
    summary = data.get("executive_summary", [])
    if summary:
        section_heading("EXECUTIVE SUMMARY")
        for point in summary[:12]:
            story.append(Paragraph(f"• {point}", styles["Bullet"]))

    # ── Core Competencies ────────────────────────────────────
    competencies = data.get("core_competencies", [])
    if competencies:
        section_heading("CORE COMPETENCIES")
        comp_data = [["Domain", "Skills", "Tools / Technologies"]]
        for c in competencies:
            comp_data.append([
                c.get("domain", ""),
                c.get("skills", ""),
                c.get("tools", ""),
            ])
        comp_table = Table(comp_data, colWidths=[4.5 * cm, 5.5 * cm, 6 * cm])
        comp_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), NAVY),
            ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_BG]),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("WORDWRAP", (0, 0), (-1, -1), True),
        ]))
        story.append(comp_table)

    # ── Employment History (nested projects) ─────────────────
    employment = data.get("employment_history", [])
    if employment:
        section_heading("EMPLOYMENT HISTORY")
        for emp in employment[:6]:
            # Company header
            duration = emp.get("duration", "")
            company_line = f"<b>{emp.get('company', '')}</b> — {emp.get('role', '')}"
            if emp.get("location"):
                company_line += f" | {emp['location']}"
            story.append(Paragraph(company_line, styles["CompanyHeader"]))
            if duration:
                story.append(Paragraph(duration, styles["SmallGray"]))

            # Nested projects
            for proj in emp.get("projects", [])[:4]:
                proj_line = f"<b>{proj.get('project_name', '')}</b>"
                if proj.get("client"):
                    proj_line += f" — {proj['client']}"
                if proj.get("duration"):
                    proj_line += f" ({proj['duration']})"
                story.append(Paragraph(proj_line, styles["ProjectHeader"]))

                for resp in proj.get("responsibilities", [])[:7]:
                    story.append(Paragraph(
                        f"• {resp}",
                        ParagraphStyle("ProjBullet", parent=styles["Bullet"], leftIndent=24),
                    ))

                if proj.get("technical_skills"):
                    story.append(Paragraph(
                        f"<i>Tech: {proj['technical_skills']}</i>",
                        ParagraphStyle("ProjTech", parent=styles["SmallGray"], leftIndent=24),
                    ))
                story.append(Spacer(1, 3))
            story.append(Spacer(1, 4))

    # Fallback: flat project_experience (old CraftQ format)
    elif data.get("project_experience"):
        section_heading("PROJECT EXPERIENCE")
        for proj in data["project_experience"][:6]:
            details = []
            if proj.get("project_name"):
                details.append(f"<b>{proj['project_name']}</b>")
            if proj.get("client"):
                details.append(f"Client: {proj['client']}")
            if proj.get("role"):
                details.append(f"Role: {proj['role']}")
            if proj.get("duration"):
                details.append(proj["duration"])
            story.append(Paragraph(" | ".join(details), styles["Body"]))
            for resp in proj.get("responsibilities", [])[:7]:
                story.append(Paragraph(f"• {resp}", styles["Bullet"]))
            story.append(Spacer(1, 4))

    # ── Education & Certifications ───────────────────────────
    section_heading("EDUCATION & CERTIFICATIONS")

    education = data.get("education", [])
    for edu in education:
        parts = []
        if edu.get("degree"):
            parts.append(f"<b>{edu['degree']}</b>")
        if edu.get("institution"):
            parts.append(edu["institution"])
        if edu.get("year"):
            parts.append(str(edu["year"]))
        story.append(Paragraph(" — ".join(parts), styles["Body"]))

    certs = data.get("certifications", [])
    if certs:
        story.append(Spacer(1, 4))
        cert_data = [["Certification", "Issuer", "Expiry"]]
        for cert in certs:
            if isinstance(cert, str):
                cert_data.append([cert, "—", "—"])
            else:
                cert_data.append([
                    cert.get("name", ""),
                    cert.get("issuer", "—"),
                    cert.get("expiry") or "⚠ Not specified",
                ])
        cert_table = Table(cert_data, colWidths=[7.5 * cm, 4 * cm, 4.5 * cm])
        cert_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), NAVY),
            ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("WORDWRAP", (0, 0), (-1, -1), True),
        ]))
        story.append(cert_table)

    # ── Technical Competencies ───────────────────────────────
    tech = data.get("technical_competencies", {})
    if tech and any(tech.values()):
        section_heading("TECHNICAL COMPETENCIES")
        for label, key in [
            ("Programming Languages", "programming_languages"),
            ("Tools & Technologies", "tools_technologies"),
            ("Platforms", "platforms"),
        ]:
            if tech.get(key):
                story.append(Paragraph(f"<b>{label}:</b> {tech[key]}", styles["Body"]))

    # ── Build ────────────────────────────────────────────────
    doc.build(
        story,
        onFirstPage=lambda c, d: _add_footer(c, d, company_name, logo_path),
        onLaterPages=lambda c, d: _add_footer(c, d, company_name, logo_path),
    )
    buffer.seek(0)
    return buffer.getvalue()


# ═════════════════════════════════════════════════════════════
# 2. SCORECARD PDF (matches existing ScorQ design exactly)
# ═════════════════════════════════════════════════════════════

def generate_scorecard_pdf(
    candidate_name: str,
    candidate_email: str,
    candidate_phone: str,
    overall_score: int,
    category_scores: dict,
    matched_skills: list,
    missing_skills: list,
    highlights: list,
    red_flags: list,
    ai_reasoning: str,
    job_title: str = "",
    logo_path: str = None,
) -> bytes:
    """Generate ScorQ scorecard PDF matching the existing design."""
    buffer = io.BytesIO()
    styles = _get_styles()

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=1.5 * cm, rightMargin=1.5 * cm,
        topMargin=1.2 * cm, bottomMargin=2.2 * cm,
    )

    story = _build_scorecard_story(
        styles, candidate_name, candidate_email, candidate_phone,
        overall_score, category_scores, matched_skills, missing_skills,
        highlights, red_flags, ai_reasoning, job_title, logo_path,
    )

    doc.build(
        story,
        onFirstPage=lambda c, d: _add_footer(c, d, "HYROI Solutions", logo_path),
        onLaterPages=lambda c, d: _add_footer(c, d, "HYROI Solutions", logo_path),
    )
    buffer.seek(0)
    return buffer.getvalue()


def _build_scorecard_story(
    styles, candidate_name, candidate_email, candidate_phone,
    overall_score, category_scores, matched_skills, missing_skills,
    highlights, red_flags, ai_reasoning, job_title, logo_path,
):
    """Build the scorecard story elements (reusable for combined PDF)."""
    story = []

    # ── ScorQ header ─────────────────────────────────────────
    brand_left = Paragraph(
        '<b><font color="#FFFFFF">Scor</font>'
        '<font color="#C8963E">Q</font></b>'
        '<font color="#8899AA" size="7">  by HYROI Solutions</font>',
        ParagraphStyle("Brand", fontName="Helvetica-Bold", fontSize=14),
    )
    brand_sub = Paragraph(
        "AI-powered resume scoring",
        ParagraphStyle("BrandSub", fontName="Helvetica", fontSize=8, textColor=colors.HexColor("#8899AA")),
    )
    date_text = Paragraph(
        f"CANDIDATE SCORECARD<br/>{datetime.now().strftime('%d %B %Y')}",
        ParagraphStyle("DateR", fontName="Helvetica", fontSize=8,
            textColor=colors.HexColor("#B0C4DE"), alignment=TA_RIGHT),
    )
    header_table = Table(
        [[[brand_left, brand_sub], date_text]],
        colWidths=[12 * cm, 4 * cm],
    )
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (0, 0), 12),
        ("RIGHTPADDING", (-1, -1), (-1, -1), 12),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(header_table)

    # ── Candidate info + score boxes ─────────────────────────
    name_para = Paragraph(
        f"<b>{candidate_name}</b>",
        ParagraphStyle("CandName", fontName="Helvetica-Bold", fontSize=18, textColor=NAVY),
    )
    contact_parts = []
    if candidate_email:
        contact_parts.append(f"✉ {candidate_email}")
    if candidate_phone:
        contact_parts.append(f"📞 {candidate_phone}")
    contact_para = Paragraph(
        "   ".join(contact_parts),
        ParagraphStyle("Contact", fontName="Helvetica", fontSize=9, textColor=GRAY),
    )

    # Score category boxes
    cat_configs = [
        ("Technical", "technical", BLUE),
        ("Experience", "experience", GREEN),
        ("Education", "education", PURPLE),
        ("Stability", "stability", GREEN),
    ]
    score_boxes = []
    for label, key, color in cat_configs:
        val = category_scores.get(key, {})
        sc = val.get("score") if isinstance(val, dict) else val
        score_boxes.append(Paragraph(
            f'<font color="{color.hexval()}" size="8"><b>{label}</b></font><br/>'
            f'<font color="{color.hexval()}" size="18"><b>{sc}%</b></font>' if sc is not None else
            f'<font color="{color.hexval()}" size="8"><b>{label}</b></font><br/>'
            f'<font color="#D1D5DB" size="18"><b>—</b></font>',
            ParagraphStyle("ScoreBox", alignment=TA_CENTER),
        ))

    info_table = Table(
        [[[name_para, contact_para], score_boxes]],
        colWidths=[8 * cm, 8 * cm],
    )
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("LEFTPADDING", (0, 0), (0, 0), 12),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 8))

    # ── Score Breakdown ──────────────────────────────────────
    story.append(Paragraph("SCORE BREAKDOWN", styles["SectionHeading"]))
    story.append(Spacer(1, 4))

    for label, key, color in cat_configs:
        val = category_scores.get(key, {})
        sc = val.get("score") if isinstance(val, dict) else val
        reasoning = val.get("reasoning", "") if isinstance(val, dict) else ""

        story.append(Paragraph(
            f'<font color="{color.hexval()}"><b>{label}</b></font>'
            f'   <font color="{color.hexval()}" size="12"><b>{sc}%</b></font>' if sc else
            f'<font color="{color.hexval()}"><b>{label}</b></font>'
            f'   <font color="#D1D5DB" size="12"><b>—</b></font>',
            ParagraphStyle("CatHead", fontName="Helvetica-Bold", fontSize=10, spaceAfter=2),
        ))
        if reasoning:
            story.append(Paragraph(reasoning, styles["Reasoning"]))
        story.append(Spacer(1, 4))

    # ── Matched Skills ───────────────────────────────────────
    story.append(Paragraph("MATCHED SKILLS", styles["SectionHeading"]))
    if matched_skills:
        skills_text = "   ".join([f"[{s}]" for s in matched_skills[:12]])
        story.append(Paragraph(skills_text, styles["Body"]))
    story.append(Spacer(1, 6))

    # ── Highlights ───────────────────────────────────────────
    if highlights:
        story.append(Paragraph("HIGHLIGHTS", styles["SectionHeading"]))
        for h in highlights[:6]:
            story.append(Paragraph(f"▸ {h}", styles["Bullet"]))
        story.append(Spacer(1, 6))

    # ── AI Assessment ────────────────────────────────────────
    if ai_reasoning:
        story.append(Paragraph("AI ASSESSMENT", styles["SectionHeading"]))
        # Warm background box effect via table
        assess_table = Table(
            [[Paragraph(ai_reasoning, styles["Reasoning"])]],
            colWidths=[16 * cm],
        )
        assess_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FFF7ED")),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("ROUNDEDCORNERS", [6, 6, 6, 6]),
        ]))
        story.append(assess_table)

    return story


# ═════════════════════════════════════════════════════════════
# 3. COMBINED PDF (resume + scorecard as last page)
# ═════════════════════════════════════════════════════════════

def generate_combined_pdf(
    # Resume data
    resume_data: dict,
    company_name: str = "HYROI Solutions",
    mask_contacts: bool = False,
    # Scorecard data
    candidate_name: str = "",
    candidate_email: str = None,
    candidate_phone: str = None,
    overall_score: int = 0,
    category_scores: dict = None,
    matched_skills: list = None,
    missing_skills: list = None,
    highlights: list = None,
    red_flags: list = None,
    ai_reasoning: str = "",
    job_title: str = "",
    logo_path: str = None,
) -> bytes:
    """
    Combined PDF: crafted resume pages followed by full ScorQ scorecard.
    Action items are NOT included.
    """
    buffer = io.BytesIO()
    styles = _get_styles()

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        leftMargin=1.5 * cm, rightMargin=1.5 * cm,
        topMargin=1.2 * cm, bottomMargin=2.2 * cm,
    )

    # Build resume story first
    # (We inline the resume building here to share the same doc)
    story = []

    # === RESUME PAGES ===
    candidate = resume_data.get("candidate_info", {})
    contact_parts = []
    if not mask_contacts:
        if candidate.get("phone"):
            contact_parts.append(candidate["phone"])
        if candidate.get("email"):
            contact_parts.append(candidate["email"])
    if candidate.get("current_location") or candidate.get("location"):
        contact_parts.append(candidate.get("current_location") or candidate.get("location"))

    name_para = Paragraph(
        candidate.get("full_name", "CANDIDATE").upper(), styles["NameStyle"]
    )
    contact_para = Paragraph(" | ".join(contact_parts), styles["ContactStyle"])
    header_table = Table([[[name_para, contact_para]]], colWidths=[16 * cm])
    header_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 8))

    def section_heading(text):
        story.append(Paragraph(text, styles["SectionHeading"]))
        story.append(HRFlowable(width="100%", thickness=0.5, color=LIGHT_NAVY, spaceAfter=4))

    # Summary
    summary = resume_data.get("executive_summary", [])
    if summary:
        section_heading("EXECUTIVE SUMMARY")
        for p in summary[:12]:
            story.append(Paragraph(f"• {p}", styles["Bullet"]))

    # Competencies
    comps = resume_data.get("core_competencies", [])
    if comps:
        section_heading("CORE COMPETENCIES")
        cd = [["Domain", "Skills", "Tools / Technologies"]]
        for c in comps:
            cd.append([c.get("domain", ""), c.get("skills", ""), c.get("tools", "")])
        ct = Table(cd, colWidths=[4.5 * cm, 5.5 * cm, 6 * cm])
        ct.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), NAVY), ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_BG]),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("LEFTPADDING", (0, 0), (-1, -1), 6), ("WORDWRAP", (0, 0), (-1, -1), True),
        ]))
        story.append(ct)

    # Employment
    employment = resume_data.get("employment_history", [])
    if employment:
        section_heading("EMPLOYMENT HISTORY")
        for emp in employment[:6]:
            cl = f"<b>{emp.get('company', '')}</b> — {emp.get('role', '')}"
            if emp.get("location"):
                cl += f" | {emp['location']}"
            story.append(Paragraph(cl, styles["CompanyHeader"]))
            if emp.get("duration"):
                story.append(Paragraph(emp["duration"], styles["SmallGray"]))
            for proj in emp.get("projects", [])[:4]:
                pl = f"<b>{proj.get('project_name', '')}</b>"
                if proj.get("duration"):
                    pl += f" ({proj['duration']})"
                story.append(Paragraph(pl, styles["ProjectHeader"]))
                for resp in proj.get("responsibilities", [])[:7]:
                    story.append(Paragraph(
                        f"• {resp}",
                        ParagraphStyle("PB", parent=styles["Bullet"], leftIndent=24),
                    ))
                story.append(Spacer(1, 2))
            story.append(Spacer(1, 4))

    # Education & Certs
    section_heading("EDUCATION & CERTIFICATIONS")
    for edu in resume_data.get("education", []):
        parts = [f"<b>{edu.get('degree', '')}</b>"]
        if edu.get("institution"):
            parts.append(edu["institution"])
        if edu.get("year"):
            parts.append(str(edu["year"]))
        story.append(Paragraph(" — ".join(parts), styles["Body"]))

    certs = resume_data.get("certifications", [])
    if certs:
        cert_data = [["Certification", "Issuer", "Expiry"]]
        for cert in certs:
            if isinstance(cert, str):
                cert_data.append([cert, "—", "—"])
            else:
                cert_data.append([cert.get("name", ""), cert.get("issuer", "—"),
                    cert.get("expiry") or "⚠ Not specified"])
        crt = Table(cert_data, colWidths=[7.5 * cm, 4 * cm, 4.5 * cm])
        crt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), NAVY), ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"), ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#D1D5DB")),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 3), ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(crt)

    # Tech competencies
    tech = resume_data.get("technical_competencies", {})
    if tech and any(tech.values()):
        section_heading("TECHNICAL COMPETENCIES")
        for label, key in [("Programming Languages", "programming_languages"),
            ("Tools & Technologies", "tools_technologies"), ("Platforms", "platforms")]:
            if tech.get(key):
                story.append(Paragraph(f"<b>{label}:</b> {tech[key]}", styles["Body"]))

    # === PAGE BREAK → SCORECARD ===
    story.append(PageBreak())

    scorecard_story = _build_scorecard_story(
        styles, candidate_name, candidate_email, candidate_phone,
        overall_score, category_scores or {}, matched_skills or [],
        missing_skills or [], highlights or [], red_flags or [],
        ai_reasoning, job_title, logo_path,
    )
    story.extend(scorecard_story)

    # Build
    doc.build(
        story,
        onFirstPage=lambda c, d: _add_footer(c, d, company_name, logo_path),
        onLaterPages=lambda c, d: _add_footer(c, d, company_name, logo_path),
    )
    buffer.seek(0)
    return buffer.getvalue()
